import { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "AERO-X1",
    category: "men",
    subType: "running",
    gender: "men",
    price: 340,
    description: "Ultra-lightweight performance runner designed for speed and agility.",
    images: ["/images/men-running-shoes-1.avif", "/images/men-running-shoes-2.avif"],
    colors: ["#FFFFFF", "#111111"],
    sizes: ["7", "8", "9", "10", "11"],
    details: ["Carbon plate", "React-Z foam"],
    isFeatured: true,
    isNew: true,
    onSale: false,
  },
  {
    id: "2",
    name: "AURAX MONO",
    category: "men",
    subType: "sneakers",
    gender: "men",
    price: 280,
    description: "Hand-crafted Italian leather with a focus on pure form.",
    images: ["/images/men-sneakers-shoes-1.avif", "/images/men-sneakers-shoes-2.avif"],
    colors: ["#000000", "#F5F5F7"],
    sizes: ["8", "9", "10", "11"],
    details: ["Italian calfskin", "Margom sole"],
    isFeatured: true,
    isNew: false,
    onSale: false,
  },
  {
    id: "3",
    name: "VOID-TECH",
    category: "men",
    subType: "sneakers",
    gender: "unisex",
    price: 450,
    description: "Architectural elements with a multi-layered cushioning system.",
    images: ["/images/men-sneakers-shoes-1.avif", "/images/men-sneakers-shoes-2.avif"],
    colors: ["#111111", "#C0C0C0"],
    sizes: ["9", "10", "11", "12"],
    details: ["Gore-Tex", "Vibram sole"],
    isFeatured: true,
    isNew: false,
    onSale: true,
  },
  {
    id: "4",
    name: "APEX RUNNER",
    category: "women",
    subType: "running",
    gender: "women",
    price: 260,
    description: "High-rebound cushioning for long distance daily wear.",
    images: ["/images/men-running-shoes-1.avif", "/images/men-running-shoes-2.avif"],
    colors: ["#E0E0E0", "#111111"],
    sizes: ["7", "8", "9", "10"],
    details: ["Breathable mesh", "TPU support"],
    isNew: false,
    onSale: true,
  },
  {
    id: "5",
    name: "REIGN L-E",
    category: "men",
    subType: "trainers",
    gender: "men",
    price: 890,
    description: "Exclusive production featuring rare technical materials.",
    images: ["/images/men-training-shoes-1.webp", "/images/men-training-shoes-2.webp"],
    colors: ["#D4D4D8", "#111111"],
    sizes: ["9", "10", "11"],
    details: ["Numbered", "VIP Auth"],
    isNew: true,
    onSale: false,
  },
  {
    id: "6",
    name: "NOVA LUX",
    category: "women",
    subType: "sneakers",
    gender: "women",
    price: 520,
    description: "Sleek, polished, and unmistakably premium high-fashion.",
    images: ["/images/men-sneakers-shoes-1.avif", "/images/men-sneakers-shoes-2.avif"],
    colors: ["#FFFFFF", "#000000"],
    sizes: ["7", "8", "9", "10"],
    details: ["Nappa leather", "Gold accents"],
    isNew: false,
    onSale: false,
  },
  {
    id: "7",
    name: "KINETIC FLOW",
    category: "men",
    subType: "running",
    gender: "men",
    price: 210,
    description: "Adaptive energy-return sole unit for city exploration.",
    images: ["/images/men-running-shoes-1.avif", "/images/men-running-shoes-2.avif"],
    colors: ["#111111", "#3B82F6"],
    sizes: ["8", "9", "10", "11"],
    details: ["TPU core", "Reflective"],
    isNew: false,
    onSale: false,
  },
  {
    id: "8",
    name: "URBAN ARCHITECT",
    category: "men",
    subType: "boots",
    gender: "men",
    price: 310,
    description: "Structured silhouette with rugged materials for concrete landscapes.",
    images: ["/images/men-boots-1.avif", "/images/men-boots-2.avif"],
    colors: ["#71717A", "#111111"],
    sizes: ["9", "10", "11", "12"],
    details: ["Ballistic nylon", "Metal eyelets"],
    isNew: false,
    onSale: false,
  },
  {
    id: "9",
    name: "VELOCITY PRO",
    category: "men",
    subType: "running",
    gender: "men",
    price: 380,
    description: "Engineered for marathon pacing with high-density foam responsiveness.",
    images: ["/images/men-running-shoes-1.avif", "/images/men-running-shoes-2.avif"],
    colors: ["#3B82F6", "#FFFFFF"],
    sizes: ["8", "9", "10", "11"],
    details: ["Energy return", "Lightweight knit"],
    isNew: true,
    onSale: false,
  },
  {
    id: "10",
    name: "ZEPHYR SANDAL",
    category: "women",
    subType: "sandals",
    gender: "women",
    price: 150,
    description: "Minimalist aesthetic meets ergonomic comfort for warm weather.",
    images: ["/images/men-sandals-1.avif", "/images/men-sandals-2.avif"],
    colors: ["#F5F5F7", "#D4D4D8"],
    sizes: ["6", "7", "8", "9"],
    details: ["Contoured footbed", "Adjustable straps"],
    isNew: false,
    onSale: true,
  },
  {
    id: "11",
    name: "TITAN BOOT",
    category: "men",
    subType: "boots",
    gender: "men",
    price: 550,
    description: "Industrial design combined with weather-resistant technical fabrics.",
    images: ["/images/men-boots-1.avif", "/images/men-boots-2.avif"],
    colors: ["#111111"],
    sizes: ["9", "10", "11"],
    details: ["Waterproof membrane", "Reinforced heel"],
    isNew: true,
    onSale: false,
  },
  {
    id: "12",
    name: "NEO-TRAINER",
    category: "men",
    subType: "trainers",
    gender: "unisex",
    price: 220,
    description: "Versatile gym trainer optimized for cross-training stability.",
    images: ["/images/men-training-shoes-1.webp", "/images/men-training-shoes-2.webp"],
    colors: ["#E0E0E0", "#000000"],
    sizes: ["7", "8", "9", "10", "11"],
    details: ["Lateral support", "Non-slip sole"],
    isNew: false,
    onSale: false,
  },
  {
    id: "13",
    name: "SUMMIT RUNNER",
    category: "men",
    subType: "running",
    gender: "men",
    price: 410,
    description: "Traction-focused trail runner for rugged elevation changes.",
    images: ["/images/men-running-shoes-1.avif", "/images/men-running-shoes-2.avif"],
    colors: ["#3B82F6", "#111111"],
    sizes: ["8", "9", "10", "11"],
    details: ["Deep lug pattern", "Rock plate"],
    isNew: false,
    onSale: true,
  },
  {
    id: "14",
    name: "AURA PLATFORM",
    category: "women",
    subType: "platforms",
    gender: "women",
    price: 320,
    description: "Elevated silhouette with premium leather finish.",
    images: ["/images/men-platform-shoes-1.webp", "/images/men-platform-shoes-2.webp"],
    colors: ["#FFFFFF", "#F5F5F7"],
    sizes: ["6", "7", "8"],
    details: ["Cushioned platform", "Full-grain leather"],
    isNew: true,
    onSale: false,
  },
  {
    id: "15",
    name: "CORE TRAINER",
    category: "women",
    subType: "trainers",
    gender: "women",
    price: 190,
    description: "Essential daily trainer for casual wear and light activity.",
    images: ["/images/men-training-shoes-1.webp", "/images/men-training-shoes-2.webp"],
    colors: ["#D4D4D8", "#000000"],
    sizes: ["6", "7", "8", "9"],
    details: ["Breathable mesh", "Soft foam"],
    isNew: false,
    onSale: true,
  },
  {
    id: "16",
    name: "APEX BOOT",
    category: "men",
    subType: "boots",
    gender: "men",
    price: 480,
    description: "Classic boot construction with modern ergonomic updates.",
    images: ["/images/men-boots-1.avif", "/images/men-boots-2.avif"],
    colors: ["#111111"],
    sizes: ["9", "10", "11", "12"],
    details: ["Waxed leather", "Slip-resistant"],
    isNew: false,
    onSale: false,
  },
  {
    id: "17",
    name: "KINETIC SANDAL",
    category: "men",
    subType: "sandals",
    gender: "men",
    price: 120,
    description: "Technical sandal designed for travel and exploration.",
    images: ["/images/men-sandals-1.avif", "/images/men-sandals-2.avif"],
    colors: ["#111111", "#71717A"],
    sizes: ["8", "9", "10", "11"],
    details: ["Quick-dry", "Supportive sole"],
    isNew: true,
    onSale: false,
  },
  {
    id: "18",
    name: "VOID RUNNER",
    category: "men",
    subType: "running",
    gender: "men",
    price: 360,
    description: "Minimalist design for high-tempo training sessions.",
    images: ["/images/men-running-shoes-1.avif", "/images/men-running-shoes-2.avif"],
    colors: ["#FFFFFF", "#000000"],
    sizes: ["8", "9", "10", "11"],
    details: ["Ultra-light", "Adaptive fit"],
    isNew: false,
    onSale: false,
  },
  {
    id: "19",
    name: "LUNA PLATFORM",
    category: "women",
    subType: "platforms",
    gender: "women",
    price: 350,
    description: "High-fashion platform with luxurious velvet textures.",
    images: ["/images/men-platform-shoes-1.webp", "/images/men-platform-shoes-2.webp"],
    colors: ["#000000", "#D4D4D8"],
    sizes: ["6", "7", "8"],
    details: ["Velvet finish", "Platform sole"],
    isNew: true,
    onSale: false,
  },
  {
    id: "20",
    name: "ZENITH TRAINER",
    category: "men",
    subType: "trainers",
    gender: "men",
    price: 240,
    description: "All-day trainer with clean, modern lines.",
    images: ["/images/men-training-shoes-1.webp", "/images/men-training-shoes-2.webp"],
    colors: ["#E0E0E0", "#FFFFFF"],
    sizes: ["8", "9", "10", "11"],
    details: ["Memory foam", "Minimal stitching"],
    isNew: false,
    onSale: true,
  },
  {
    id: "21",
    name: "ONYX RUNNER",
    category: "men",
    subType: "running",
    gender: "men",
    price: 390,
    description: "All-black performance runner designed for durability.",
    images: ["/images/men-running-shoes-1.avif", "/images/men-running-shoes-2.avif"],
    colors: ["#111111"],
    sizes: ["9", "10", "11", "12"],
    details: ["Reinforced mesh", "Traction sole"],
    isNew: true,
    onSale: false,
  },
  {
    id: "22",
    name: "VALLEY SANDAL",
    category: "women",
    subType: "sandals",
    gender: "women",
    price: 110,
    description: "Lightweight, water-ready sandal for casual city wear.",
    images: ["/images/men-sandals-1.avif", "/images/men-sandals-2.avif"],
    colors: ["#FFFFFF", "#D4D4D8"],
    sizes: ["6", "7", "8"],
    details: ["Ergonomic sole", "Water-resistant"],
    isNew: false,
    onSale: true,
  },
  {
    id: "23",
    name: "URBAN BOOT II",
    category: "men",
    subType: "boots",
    gender: "men",
    price: 330,
    description: "Refined urban boot with a focus on all-day wearability.",
    images: ["/images/men-boots-1.avif", "/images/men-boots-2.avif"],
    colors: ["#71717A", "#000000"],
    sizes: ["9", "10", "11"],
    details: ["Supple leather", "Cushioned insole"],
    isNew: false,
    onSale: false,
  },
  {
    id: "24",
    name: "FLOW TRAINER",
    category: "women",
    subType: "trainers",
    gender: "women",
    price: 200,
    description: "Streamlined training shoe for daily movement.",
    images: ["/images/men-training-shoes-1.webp", "/images/men-training-shoes-2.webp"],
    colors: ["#F5F5F7", "#D4D4D8"],
    sizes: ["6", "7", "8", "9"],
    details: ["Flexible sole", "Breathable"],
    isNew: false,
    onSale: false,
  },
  {
    id: "25",
    name: "METRO RUNNER",
    category: "men",
    subType: "running",
    gender: "men",
    price: 270,
    description: "A classic runner profile reimagined for urban environments.",
    images: ["/images/men-running-shoes-1.avif", "/images/men-running-shoes-2.avif"],
    colors: ["#E0E0E0", "#000000"],
    sizes: ["8", "9", "10", "11"],
    details: ["Durable mesh", "Responsive heel"],
    isNew: true,
    onSale: false,
  },
  {
    id: "26",
    name: "PRISM PLATFORM",
    category: "women",
    subType: "platforms",
    gender: "women",
    price: 380,
    description: "Bold platform design with reflective color-shifting accents.",
    images: ["/images/men-platform-shoes-1.webp", "/images/men-platform-shoes-2.webp"],
    colors: ["#FFFFFF", "#3B82F6"],
    sizes: ["6", "7", "8"],
    details: ["Iridescent finish", "Platform sole"],
    isNew: true,
    onSale: false,
  },
  {
    id: "27",
    name: "SOLO BOOT",
    category: "men",
    subType: "boots",
    gender: "men",
    price: 420,
    description: "Minimalist boot designed for maximum versatility.",
    images: ["/images/men-boots-1.avif", "/images/men-boots-2.avif"],
    colors: ["#000000"],
    sizes: ["9", "10", "11"],
    details: ["Hidden laces", "Smooth leather"],
    isNew: false,
    onSale: true,
  },
  {
    id: "28",
    name: "AERO SANDAL",
    category: "women",
    subType: "sandals",
    gender: "women",
    price: 130,
    description: "Ultra-lightweight sandal designed for maximum airflow.",
    images: ["/images/men-sandals-1.avif", "/images/men-sandals-2.avif"],
    colors: ["#F5F5F7", "#FFFFFF"],
    sizes: ["6", "7", "8", "9"],
    details: ["Anatomical fit", "Weightless"],
    isNew: false,
    onSale: false,
  },
  {
    id: "29",
    name: "VANGUARD RUNNER",
    category: "men",
    subType: "running",
    gender: "men",
    price: 290,
    description: "High-performance urban runner with adaptive mesh.",
    images: ["/images/men-running-shoes-1.avif", "/images/men-running-shoes-2.avif"],
    colors: ["#111111"],
    sizes: ["8", "9", "10", "11"],
    details: ["Reflective trim", "EVA sole"],
    isNew: true,
    onSale: false,
  },
  {
    id: "30",
    name: "ZENITH PLATFORM",
    category: "women",
    subType: "platforms",
    gender: "women",
    price: 310,
    description: "Sculptural platform with a minimalist leather upper.",
    images: ["/images/men-platform-shoes-1.webp", "/images/men-platform-shoes-2.webp"],
    colors: ["#FFFFFF"],
    sizes: ["6", "7", "8"],
    details: ["Hidden wedge", "Soft lining"],
    isNew: false,
    onSale: false,
  },
  {
    id: "31",
    name: "TERRA BOOT",
    category: "men",
    subType: "boots",
    gender: "men",
    price: 450,
    description: "Rugged all-terrain boot for outdoor exploration.",
    images: ["/images/men-boots-1.avif", "/images/men-boots-2.avif"],
    colors: ["#45332E"],
    sizes: ["9", "10", "11", "12"],
    details: ["Waterproof", "Lug outsole"],
    isNew: false,
    onSale: true,
  },
  {
    id: "32",
    name: "KINETIC TRAINER",
    category: "men",
    subType: "trainers",
    gender: "men",
    price: 180,
    description: "Lightweight training shoe for gym mobility.",
    images: ["/images/men-training-shoes-1.webp", "/images/men-training-shoes-2.webp"],
    colors: ["#D4D4D8"],
    sizes: ["8", "9", "10"],
    details: ["Ankle support", "Flex grooves"],
    isNew: true,
    onSale: false,
  },
  {
    id: "33",
    name: "LUNA SANDAL",
    category: "women",
    subType: "sandals",
    gender: "women",
    price: 95,
    description: "Summer-ready strap sandal with cushioned base.",
    images: ["/images/men-sandals-1.avif", "/images/men-sandals-2.avif"],
    colors: ["#F5F5F7"],
    sizes: ["6", "7", "8"],
    details: ["Buckle closure", "Arch support"],
    isNew: false,
    onSale: true,
  },
  {
    id: "34",
    name: "ALPHA SNEAKER",
    category: "men",
    subType: "sneakers",
    gender: "men",
    price: 220,
    description: "A classic low-top sneaker for daily style.",
    images: ["/images/men-sneakers-shoes-1.avif", "/images/men-sneakers-shoes-2.avif"],
    colors: ["#FFFFFF", "#000000"],
    sizes: ["8", "9", "10", "11"],
    details: ["Canvas upper", "Vulcanized sole"],
    isNew: false,
    onSale: false,
  },
  {
    id: "35",
    name: "OMEGA RUNNER",
    category: "men",
    subType: "running",
    gender: "men",
    price: 320,
    description: "Long-distance runner with high energy return.",
    images: ["/images/men-running-shoes-1.avif", "/images/men-running-shoes-2.avif"],
    colors: ["#3B82F6"],
    sizes: ["9", "10", "11"],
    details: ["Knit upper", "Carbon plate"],
    isNew: true,
    onSale: false,
  },
  {
    id: "36",
    name: "SILVER PLATFORM",
    category: "women",
    subType: "platforms",
    gender: "women",
    price: 360,
    description: "Statement platform with metallic finish.",
    images: ["/images/men-platform-shoes-1.webp", "/images/men-platform-shoes-2.webp"],
    colors: ["#C0C0C0"],
    sizes: ["6", "7", "8"],
    details: ["Glossy finish", "Platform sole"],
    isNew: true,
    onSale: false,
  },
  {
    id: "37",
    name: "GALA BOOT",
    category: "men",
    subType: "boots",
    gender: "men",
    price: 390,
    description: "Premium leather chelsea boot for formal wear.",
    images: ["/images/men-boots-1.avif", "/images/men-boots-2.avif"],
    colors: ["#000000"],
    sizes: ["9", "10", "11"],
    details: ["Elastic gore", "Leather sole"],
    isNew: false,
    onSale: false,
  },
  {
    id: "38",
    name: "BEAM TRAINER",
    category: "women",
    subType: "trainers",
    gender: "women",
    price: 210,
    description: "High-vis trainer for evening workouts.",
    images: ["/images/men-training-shoes-1.webp", "/images/men-training-shoes-2.webp"],
    colors: ["#3B82F6"],
    sizes: ["6", "7", "8"],
    details: ["Reflective mesh", "Cushioned"],
    isNew: true,
    onSale: false,
  },
  {
    id: "39",
    name: "SHORE SANDAL",
    category: "men",
    subType: "sandals",
    gender: "men",
    price: 85,
    description: "Sturdy summer sandal for beach and city.",
    images: ["/images/men-sandals-1.avif", "/images/men-sandals-2.avif"],
    colors: ["#71717A"],
    sizes: ["8", "9", "10", "11"],
    details: ["Quick-dry", "Support"],
    isNew: false,
    onSale: true,
  },
  {
    id: "40",
    name: "DASH SNEAKER",
    category: "men",
    subType: "sneakers",
    gender: "men",
    price: 190,
    description: "Lightweight casual sneaker with ergonomic fit.",
    images: ["/images/men-sneakers-shoes-1.avif", "/images/men-sneakers-shoes-2.avif"],
    colors: ["#D4D4D8"],
    sizes: ["8", "9", "10"],
    details: ["Breathable", "Padded tongue"],
    isNew: false,
    onSale: false,
  },
  {
    id: "41",
    name: "APEX RUNNER II",
    category: "men",
    subType: "running",
    gender: "men",
    price: 340,
    description: "Improved stability runner for heavy usage.",
    images: ["/images/men-running-shoes-1.avif", "/images/men-running-shoes-2.avif"],
    colors: ["#111111"],
    sizes: ["9", "10", "11"],
    details: ["Reinforced heel", "Grip"],
    isNew: true,
    onSale: false,
  },
  {
    id: "42",
    name: "VIVA PLATFORM",
    category: "women",
    subType: "platforms",
    gender: "women",
    price: 280,
    description: "Fun platform with pop-color details.",
    images: ["/images/men-platform-shoes-1.webp", "/images/men-platform-shoes-2.webp"],
    colors: ["#FFFFFF", "#3B82F6"],
    sizes: ["6", "7", "8"],
    details: ["Rubber sole", "Light"],
    isNew: false,
    onSale: false,
  },
  {
    id: "43",
    name: "URBAN BOOT III",
    category: "men",
    subType: "boots",
    gender: "men",
    price: 500,
    description: "Hand-stitched leather boot with durable soul.",
    images: ["/images/men-boots-1.avif", "/images/men-boots-2.avif"],
    colors: ["#111111"],
    sizes: ["9", "10", "11"],
    details: ["Waxed", "Goodyear welt"],
    isNew: true,
    onSale: false,
  },
  {
    id: "44",
    name: "FLEX TRAINER",
    category: "men",
    subType: "trainers",
    gender: "men",
    price: 170,
    description: "Minimal trainer for maximum foot freedom.",
    images: ["/images/men-training-shoes-1.webp", "/images/men-training-shoes-2.webp"],
    colors: ["#E0E0E0"],
    sizes: ["8", "9", "10"],
    details: ["Flexible", "Light"],
    isNew: false,
    onSale: true,
  },
  {
    id: "45",
    name: "SUN SANDAL",
    category: "women",
    subType: "sandals",
    gender: "women",
    price: 105,
    description: "Elegant strap sandal for warm evenings.",
    images: ["/images/men-sandals-1.avif", "/images/men-sandals-2.avif"],
    colors: ["#F5F5F7"],
    sizes: ["6", "7", "8"],
    details: ["Soft strap", "Flat"],
    isNew: false,
    onSale: false,
  },
  {
    id: "46",
    name: "MOD SNEAKER",
    category: "men",
    subType: "sneakers",
    gender: "men",
    price: 230,
    description: "Modern take on a classic court sneaker.",
    images: ["/images/men-sneakers-shoes-1.avif", "/images/men-sneakers-shoes-2.avif"],
    colors: ["#FFFFFF"],
    sizes: ["8", "9", "10"],
    details: ["Leather", "Padded"],
    isNew: false,
    onSale: false,
  },
  {
    id: "47",
    name: "PEAK RUNNER",
    category: "men",
    subType: "running",
    gender: "men",
    price: 420,
    description: "Trail-ready beast for high mountains.",
    images: ["/images/men-running-shoes-1.avif", "/images/men-running-shoes-2.avif"],
    colors: ["#45332E"],
    sizes: ["9", "10", "11"],
    details: ["Spikes", "Waterproof"],
    isNew: true,
    onSale: false,
  },
  {
    id: "48",
    name: "STAR PLATFORM",
    category: "women",
    subType: "platforms",
    gender: "women",
    price: 330,
    description: "Glitter-finish platform for nightlife.",
    images: ["/images/men-platform-shoes-1.webp", "/images/men-platform-shoes-2.webp"],
    colors: ["#000000"],
    sizes: ["6", "7", "8"],
    details: ["Sequins", "Platform"],
    isNew: true,
    onSale: false,
  },
  {
    id: "49",
    name: "RIDGE BOOT",
    category: "men",
    subType: "boots",
    gender: "men",
    price: 370,
    description: "Mid-height utility boot with metal hooks.",
    images: ["/images/men-boots-1.avif", "/images/men-boots-2.avif"],
    colors: ["#71717A"],
    sizes: ["9", "10", "11"],
    details: ["Hook lacing", "Durable"],
    isNew: false,
    onSale: true,
  },
  {
    id: "50",
    name: "CORE TRAINER II",
    category: "women",
    subType: "trainers",
    gender: "women",
    price: 220,
    description: "Advanced training shoe with extra stability.",
    images: ["/images/men-training-shoes-1.webp", "/images/men-training-shoes-2.webp"],
    colors: ["#D4D4D8"],
    sizes: ["6", "7", "8"],
    details: ["Stability", "Cushion"],
    isNew: false,
    onSale: false,
  },
  {
    id: "51",
    name: "BAY SANDAL",
    category: "men",
    subType: "sandals",
    gender: "men",
    price: 90,
    description: "Rugged construction for outdoor adventures.",
    images: ["/images/men-sandals-1.avif", "/images/men-sandals-2.avif"],
    colors: ["#111111"],
    sizes: ["8", "9", "10"],
    details: ["Velcro", "Traction"],
    isNew: false,
    onSale: false,
  },
  {
    id: "52",
    name: "CITY SNEAKER",
    category: "men",
    subType: "sneakers",
    gender: "men",
    price: 250,
    description: "Clean, simple aesthetic for urban commute.",
    images: ["/images/men-sneakers-shoes-1.avif", "/images/men-sneakers-shoes-2.avif"],
    colors: ["#FFFFFF"],
    sizes: ["8", "9", "10"],
    details: ["Minimal", "Durable"],
    isNew: false,
    onSale: false,
  },
  {
    id: "53",
    name: "FLY RUNNER",
    category: "men",
    subType: "running",
    gender: "men",
    price: 310,
    description: "Ultra-breezy running shoe for summer.",
    images: ["/images/men-running-shoes-1.avif", "/images/men-running-shoes-2.avif"],
    colors: ["#F5F5F7"],
    sizes: ["9", "10", "11"],
    details: ["Mesh", "Lightweight"],
    isNew: true,
    onSale: false,
  },
  {
    id: "54",
    name: "GLAM PLATFORM",
    category: "women",
    subType: "platforms",
    gender: "women",
    price: 390,
    description: "Velvet platform for formal evening wear.",
    images: ["/images/men-platform-shoes-1.webp", "/images/men-platform-shoes-2.webp"],
    colors: ["#111111"],
    sizes: ["6", "7", "8"],
    details: ["Velvet", "Sturdy"],
    isNew: true,
    onSale: false,
  },
  {
    id: "55",
    name: "PATH BOOT",
    category: "men",
    subType: "boots",
    gender: "men",
    price: 350,
    description: "Everyday brown boot for smart casual style.",
    images: ["/images/men-boots-1.avif", "/images/men-boots-2.avif"],
    colors: ["#45332E"],
    sizes: ["9", "10", "11"],
    details: ["Leather", "Flat sole"],
    isNew: false,
    onSale: true,
  },
  {
    id: "56",
    name: "SWIFT TRAINER",
    category: "women",
    subType: "trainers",
    gender: "women",
    price: 190,
    description: "Quick-start trainer for high-intensity work.",
    images: ["/images/men-training-shoes-1.webp", "/images/men-training-shoes-2.webp"],
    colors: ["#3B82F6"],
    sizes: ["6", "7", "8"],
    details: ["Agile", "Supportive"],
    isNew: false,
    onSale: false,
  },
  {
    id: "57",
    name: "DUNES SANDAL",
    category: "women",
    subType: "sandals",
    gender: "women",
    price: 120,
    description: "Comfortable slide sandal for beach relaxation.",
    images: ["/images/men-sandals-1.avif", "/images/men-sandals-2.avif"],
    colors: ["#E0E0E0"],
    sizes: ["6", "7", "8"],
    details: ["Slide", "Soft"],
    isNew: false,
    onSale: false,
  },
  {
    id: "58",
    name: "ICON SNEAKER",
    category: "men",
    subType: "sneakers",
    gender: "men",
    price: 300,
    description: "Limited edition retro-inspired sneaker.",
    images: ["/images/men-sneakers-shoes-1.avif", "/images/men-sneakers-shoes-2.avif"],
    colors: ["#111111", "#FFFFFF"],
    sizes: ["8", "9", "10"],
    details: ["Premium", "Collector"],
    isNew: true,
    onSale: false,
  },
  {
    id: "59",
    name: "WAVE RUNNER",
    category: "men",
    subType: "running",
    gender: "men",
    price: 280,
    description: "Balanced runner with soft foam cushioning.",
    images: ["/images/men-running-shoes-1.avif", "/images/men-running-shoes-2.avif"],
    colors: ["#D4D4D8"],
    sizes: ["9", "10", "11"],
    details: ["Soft", "Energy"],
    isNew: false,
    onSale: true,
  },
  {
    id: "60",
    name: "SOLO PLATFORM",
    category: "women",
    subType: "platforms",
    gender: "women",
    price: 320,
    description: "Sleek monochromatic platform sneaker.",
    images: ["/images/men-platform-shoes-1.webp", "/images/men-platform-shoes-2.webp"],
    colors: ["#000000"],
    sizes: ["6", "7", "8"],
    details: ["Sleek", "Height"],
    isNew: false,
    onSale: false,
  },
];

export const CATEGORIES = ["men", "women", "kids", "new", "sale"];
